echo Remove...
rm -r *.o *.a *.exe
echo Build...
echo -----------------
g++ -pipe -c CIni.cpp
ar rcs libCIni.a CIni.o
g++ -ggdb -enable-auto-import -pipe main.cpp -L. -lCIni -o CIniTest
echo -----------------
echo End...
